name: main
on:
  push:
    branches:
      - staging
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - uses: actions/cache@v2
        name: Load from cache
        with:
          path: |
            ${{ github.workspace }}/.next/cache
            ${{ github.workspace }}/.imageCache
          key: ${{ runner.os }}-nextjs-20210421-3-${{ hashFiles('**/package-lock.json') }}
      - name: Build
        run: yarn build
      - name: "publish"
        run: |
          npx -p "@getmeli/cli" meli upload ./out \
            --url "https://staging.random.studio" \
            --site "$MELI_SITE" \
            --token "$MELI_TOKEN" \
            --release "$GITHUB_SHA"
        env:
          MELI_SITE: "e9b24899-6b0b-4694-acec-6f849462b360"
          MELI_TOKEN: ${{ secrets.MELI_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}