name: Deploy to Leafcloud
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      SERVER_IP: 195.114.30.143
      SERVER_PORT: 22
      SOURCE_DIR: 'out'
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn
      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-20210215-${{ hashFiles('**/package-lock.json') }}
      - name: Build
        run: yarn build
      - name: Create folders
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SERVER_IP }}
          username: staging-bot
          key: ${{ secrets.SSH_KEY }}
          port: ${{ env.SERVER_PORT }}
          script: mkdir -p /var/www/staging.random.studio/${{ github.event.repository.name }}
      - name: Deploy preview
        uses: AEnterprise/rsync-deploy@1.0.1
        env:
          ARGS: "-e -c -r --delete"
          DEPLOY_KEY: ${{ secrets.SSH_KEY }}
          USERNAME: staging-bot
          FOLDER: "./${{ env.SOURCE_DIR }}/"
          SERVER_DESTINATION: '/var/www/staging.random.studio/${{ github.event.repository.name }}'
